### ISSUE TITLE
Encryption support?

### ISSUE THREAD

**Issue by ikarlashov** [DrFaust92/terraform-kubernetes-ebs-csi-driver#59]
Hey there,

We're using your code to deploy EBS-CSI driver into our EKS. There's one problem, due to security restrictions we can't create non-encrypted pvc/ebs volumes.

The current sc.yaml:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

I walked through the code and couldn't even figure out at what stage StorageClass got created. Neither the way to pass additional params to its `parameters`.

Can you pls help with that?
